import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { notFound, redirect } from "next/navigation";
import InvoiceTemplate from "@/components/InvoiceTemplate";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";
import PrintInvoiceButton from "@/components/PrintInvoiceButton";

export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const session = await getServerSession(authOptions);
  const resolvedParams = await params;

  if (!session) {
    redirect("/login");
  }

  const order = await prisma.order.findUnique({
    where: { id: resolvedParams.id },
    include: {
      user: { select: { name: true, email: true } },
      items: {
        include: { product: true }
      }
    }
  });

  if (!order) {
    notFound();
  }

  // Security check: Only Admin, Shop Manager, or the Customer who placed the order can view it
  if (session.user.role !== "SYSTEM_ADMIN" && session.user.role !== "SHOP_MANAGER" && session.user.id !== order.userId) {
    redirect("/dashboard");
  }

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 py-12 px-4 sm:px-6 lg:px-8 print:bg-white print:py-0 print:px-0">
      {/* Controls - Hidden during print */}
      <div className="max-w-[800px] mx-auto mb-8 flex items-center justify-between print:hidden">
        <Link 
          href={session.user.role === "CLIENT" ? "/dashboard/client/orders" : `/dashboard/${session.user.role.toLowerCase().replace('_', '-')}/orders/${order.id}`}
          className="flex items-center gap-2 text-sm font-black text-gray-800 uppercase tracking-widest hover:text-[var(--primary-purple)] transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>
        <div className="flex items-center gap-4">
          <PrintInvoiceButton />
        </div>
      </div>

      {/* Invoice Container */}
      <div className="max-w-[800px] mx-auto bg-white shadow-2xl shadow-purple-900/5 rounded-[40px] overflow-hidden print:shadow-none print:rounded-none">
         {/* We reuse the template but override the 'hidden' class for this specific page */}
         <div className="block">
            <InvoiceTemplate order={order} />
         </div>
      </div>
      
      {/* Footer Info */}
      <div className="max-w-[800px] mx-auto mt-8 text-center print:hidden">
        <p className="text-[10px] font-black text-gray-600 uppercase tracking-widest">
           Secure Invoice Generated by Whole Purple Operations
        </p>
      </div>

      {/* Internal script to handle print class override for this page specifically */}
      <style dangerouslySetInnerHTML={{ __html: `
        @media screen {
          #invoice-template {
            display: block !important;
          }
        }
      `}} />
    </div>
  );
}
